# Generated by Django 4.2 on 2023-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
